### PR TITLE
Landing page and components page

### PR DESCRIPTION
**Pull request by SatwikaKacham**
1. Created landing page and components page
2. added all components to component page
3. added header footer and sidebar to component page
4. [CSB](https://9oq7o.csb.app/)

### CODE REVIEW

**Comment by Meghana-sk** [comment]
one suggestion: Instead of having separate Home tab, on logo click, page can be redirected to home page

**Review by shristabaruah — APPROVED** [review]

**Comment by shristabaruah** [comment]
Nice work !

**Review by mohammed-sas — CHANGES_REQUESTED** [review]
differentiate between components either by having a horizontal line between them or make the heading of components larger. In your CL , there isn;t differentiation between subcomponents and components

**Review by aamir74 — APPROVED** [review]
Good to go.

**Pull request merged**
